"""empty message

Revision ID: c2d846cf90b8
Revises: 
Create Date: 2026-06-30 01:45:23.778757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c2d846cf90b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outlet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_outlet', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lokasi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaksilaundry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_nota', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=True),
    sa.Column('tgl_terima', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_harga', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaksilaundry')
    op.drop_table('outlet')
    # ### end Alembic commands ###
